project:
  type: book

book:
  title: "Computational Thinking with SIR Models"
  subtitle: "A Disease Ecology Module"
  author: "Anjali Tomerlin"
  chapters:
    - index.qmd
    - chapters/terms_intro.qmd
    - chapters/epidemic_model_intro.qmd
    - chapters/solving_sir.qmd
    - chapters/mle.qmd
    - chapters/recap_parameters.qmd
    - chapters/reprod_nums.qmd
    - chapters/examples.qmd

format:
  live-html:
    theme: cosmo
    number-sections: true
    toc: true
    toc-depth: 5
    toc-expand: true
    code-fold: false
    code-tools: true
    fig-align: center
    callouts: true