project:
  type: book
  output-dir: docs

book:
  title: "Computational Thinking with SIR Models"
  subtitle: "A Disease Ecology Module"
  author:
    - name: "Francisca Javiera Rudolph"
    - name: "Anjali Tomerlin"
  date: today
  chapters:
    - index.qmd
bibliography: modules/reference.bib

format:
  live-html:
    theme: cosmo
    number-sections: true
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    fig-align: center

execute:
  freeze: auto