project:
  type: book
  output-dir: docs

book:
  title: "Computational Thinking with SIR Models"
  subtitle: "A Disease Ecology Module"
  author:
    - name: "Anjali Tomerlin"
    - name: "Francisca Javiera Rudolph"
  date: today
  chapters:
      - index.qmd
      - modules/01-sir-intro/compartments.qmd
      - modules/01-sir-intro/sir_equations.qmd
      - modules/01-sir-intro/solving_sir.qmd
      - modules/01-sir-intro/fitting_mle.qmd
      - modules/01-sir-intro/reproduction_number.qmd
      - modules/01-sir-intro/case_studies.qmd


bibliography: modules/reference.bib

format:
  live-html:
    theme: cosmo
    number-sections: true
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    fig-align: center

execute:
  freeze: auto